version: 2

sources:
  - name: gz_raw_date
    description: gz dateset
    tables:
      - name: product
        description: product data
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: products id
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: purchase price
      - name: sales
        description: sales data
        identifier: raw_gz_sales
        columns:
          - name: date_date
            description: sales date
          - name: orders_id
            description: order id
          - name: pdt_id
            description: products id
          - name: revenue
            description: sales revenue
          - name: quantity
            description: quantity

      - name: ship
        description: ship data
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: order id
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping fee
          - name: logcost
            description: logistic fee
          - name: ship_cost
            description: cost for shipping


      - name: adwords
        identifier: raw_gz_adwords
        columns:
          - name: date_date
            description: date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: bing
        identifier: raw_gz_bing
        columns:
          - name: date_date
            description: date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: criteo
        identifier: raw_gz_criteo
        columns:
          - name: date_date
            description: date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      - name: facebook
        identifier: raw_gz_facebook
        columns:
          - name: date_date
            description: date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click


      

            

models:
  - name: stg_gz_raw_date__sales
    columns:
      - name: id
        tests:
          - unique

  - name: int_sales_margin
    description: calculate margin per product
    columns:
      - name: products_id
        description: products key
        tests:
          - not_null
      - name: date_date
        description: date of the order
        tests:
          - not_null
      - name: orders_id
        description: orders key
        tests:
          - not_null
      - name: purchase_price
        description: price for purchase
        tests:
          - not_null
      - name: revenue
        description: sales revenue
        tests:
          - not_null
      - name: quantity
        description: sales products quantity
        tests:
          - not_null
      - name: purchase_cost
        description: purchase_price*quantity
        tests:
          - not_null
      - name: margin
        description: revenue-purchase_cost
        tests:
          - not_null

  - name: int_orders_margin
    description: calculate margin per order
    columns:
      - name: orders_id
        description: orders key
        tests:
          - not_null
      - name: date_date
        description: date of the order
        tests:
          - not_null
      - name: revenue
        description: sum revenue
        tests:
          - not_null
      - name: quantity
        description: sum quantity
        tests:
          - not_null
      - name: purchase_cost
        description: sum purchase cost
        tests:
          - not_null
      - name: margin
        description: sum margin
        tests:
          - not_null

  - name: finance_days
    description: Daily financial kpi for finance team
    columns:
      - name: total_nb_transactions
        tests:
          - not_null
      - name: date_date
        description: date of the order
        tests:
          - not_null
      - name: operational_margin
        description: Operational_margin total
        tests:
          - not_null
      - name: total_revenue
        description: revenue
        tests:
          - not_null
      - name: total_quantity
        description: quantity
        tests:
          - not_null
      - name: total_purchase_cost
        description: sum purchase cost
        tests:
          - not_null
      - name: total_shipping_fee
        description: income
        tests:
          - not_null
      - name: total_logcost
        tests:
          - not_null
      - name: total_ship_cost
        tests:
          - not_null
      - name: average_basket
        description: total revenue/total transactions
        tests:
          - not_null

  - name: int_campaigns
    description: merge adwords,bing,criteo,facebook
    columns:
      - name: paid_source
        tests:
          - not_null
      - name: date_date
        description: date champaign
        tests:
          - not_null
      - name: campaign_key
        tests:
          - not_null
      - name: campaign_name
        description: campaign_name
        tests:
          - not_null
      - name: impression
        tests:
          - not_null
      - name: click
        tests:
          - not_null
      - name: ads_cost
        tests:
          - not_null

  - name: int_campaigns_day
    description: an aggregated version of int_campaigns model for each day.
    columns:
      - name: date_date
        description: date
        tests:
          - not_null
      - name: impression
        tests:
          - not_null
      - name: click
        tests:
          - not_null
      - name: ads_cost
        tests:
          - not_null
  - name: finance_campaigns_day
    description: merge finance_days and int_campaigns_days
    columns:
      - name: date
        tests:
          - not_null
      - name: ads_margin
        description: ads_margin = operational_margin - ads_cost
        tests:
          - not_null
      - name: average_basket
        tests:
          - not_null
      - name: ads_impression
        tests:
          - not_null
      - name: ads_clicks
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
      - name: purchase_cost
        tests:
          - not_null
      - name: shipping_fee
        tests:
          - not_null
      - name: log_cost
        tests:
          - not_null
      - name: ship_cost
        tests:
          - not_null

  - name: finance_campaigns_month
    description: aggregate by month
    columns:
      - name: datemonth
        tests:
          - not_null
      - name: ads_margin
        description: ads_margin = operational_margin - ads_cost
        tests:
          - not_null
      - name: average_basket
        tests:
          - not_null
      - name: ads_impression
        tests:
          - not_null
      - name: ads_clicks
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
      - name: purchase_cost
        tests:
          - not_null
      - name: shipping_fee
        tests:
          - not_null
      - name: log_cost
        tests:
          - not_null
      - name: ship_cost
        tests:
          - not_null
