version: 2

sources:
  - name: raw
    description: gz dateset
    identifier: gz_raw_date
    tables:
      - name: product
        description: product data
        identifier: raw_gz_product
      - name: sales
        description: sales data
        identifier: raw_gz_sales
      - name: ship
        description: ship data
        identifier: raw_gz_ship